# Generated by Django 3.1.1 on 2021-03-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210327_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_time',
            name='login_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session_time',
            name='logout_time',
            field=models.TimeField(null=True),
        ),
    ]
