# Generated by Django 3.1.1 on 2021-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210327_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_time',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session_time',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
