# Generated by Django 3.1.1 on 2021-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20210327_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_time',
            name='login_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session_time',
            name='logout_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
