# Generated by Django 3.1.1 on 2021-03-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20210327_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_time',
            name='ses_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
